<a href="https://colab.research.google.com/github/yolandaeka/DataMining_2024/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# import unecessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [9]:
df = pd.read_csv('diabetes.csv')
print(df.shape)
df.describe().transpose()

(768, 9)


count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [12]:
target_column = ['Outcome']
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%  \
Pregnancies               768.0  0.226180  0.198210  0.000000  0.058824   
Glucose                   768.0  0.607510  0.160666  0.000000  0.497487   
BloodPressure             768.0  0.566438  0.158654  0.000000  0.508197   
SkinThickness             768.0  0.207439  0.161134  0.000000  0.000000   
Insulin                   768.0  0.094326  0.136222  0.000000  0.000000   
BMI                       768.0  0.476790  0.117499  0.000000  0.406855   
DiabetesPedigreeFunction  768.0  0.194990  0.136913  0.032231  0.100723   
Age                       768.0  0.410381  0.145188  0.259259  0.296296   
Outcome                   768.0  0.348958  0.476951  0.000000  0.000000   

                               50%       75%  max  
Pregnancies               0.176471  0.352941  1.0  
Glucose                   0.587940  0.704774  1.0  
BloodPressure             0.590164  0.655738  1.0  
SkinThickness             0.232323  0.323232  1.0  
Insulin                   0.036052  0.150414  1.0  
BMI                       0.476900  0.545455  1.0  
DiabetesPedigreeFunction  0.153926  0.258781  1.0  
Age                       0.358025  0.506173  1.0  
Outcome                   0.000000  1.000000  1.0

In [15]:
x = df[predictors].values
y = df[target_column].values

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.30, random_state=40)
print(x_train.shape); print(x_test.shape)

(537, 8)
(231, 8)


In [37]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(7,10,8), activation='relu', solver='adam', max_iter=500)
mlp.fit(x_train, y_train)

predict_train = mlp.predict(x_train)
predict_test = mlp.predict(x_test)




/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1098: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[319  39]
 [ 70 109]]
              precision    recall  f1-score   support

         0.0       0.82      0.89      0.85       358
         1.0       0.74      0.61      0.67       179

    accuracy                           0.80       537
   macro avg       0.78      0.75      0.76       537
weighted avg       0.79      0.80      0.79       537



In [39]:
# Import required libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Load dataset
df = pd.read_csv('diabetes.csv')

# Normalize data
target_column = ['Outcome']
predictors = list(set(list(df.columns)) - set(target_column))
df[predictors] = df[predictors] / df[predictors].max()

# Prepare data for training and testing
X = df[predictors].values
y = df[target_column].values.ravel()  # flatten y array

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)

# List of activation functions to test
activations = ['identity', 'logistic', 'tanh', 'relu']
results = {}

for activation in activations:
    # Initialize and train the model
    mlp = MLPClassifier(hidden_layer_sizes=(7, 10, 8), activation=activation, solver='adam', max_iter=500)
    mlp.fit(x_train, y_train)

    # Predictions
    predict_train = mlp.predict(x_train)
    predict_test = mlp.predict(x_test)

    # Evaluate the model
    train_accuracy = accuracy_score(y_train, predict_train)
    test_accuracy = accuracy_score(y_test, predict_test)

    results[activation] = {
        'train_accuracy': train_accuracy,
        'test_accuracy': test_accuracy,
        'confusion_matrix': confusion_matrix(y_test, predict_test),
        'classification_report': classification_report(y_test, predict_test)
    }

# Print results
for activation, result in results.items():
    print(f"Activation Function: {activation}")
    print(f"Train Accuracy: {result['train_accuracy']}")
    print(f"Test Accuracy: {result['test_accuracy']}")
    print("Confusion Matrix:")
    print(result['confusion_matrix'])
    print("Classification Report:")
    print(result['classification_report'])
    print("--------------------------------------------------------")


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Activation Function: identity
Train Accuracy: 0.7895716945996276
Test Accuracy: 0.7359307359307359
Confusion Matrix:
[[123  19]
 [ 42  47]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.87      0.80       142
           1       0.71      0.53      0.61        89

    accuracy                           0.74       231
   macro avg       0.73      0.70      0.70       231
weighted avg       0.73      0.74      0.73       231

--------------------------------------------------------
Activation Function: logistic
Train Accuracy: 0.6666666666666666
Test Accuracy: 0.6147186147186147
Confusion Matrix:
[[142   0]
 [ 89   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.61      1.00      0.76       142
           1       0.00      0.00      0.00        89

    accuracy                           0.61       231
   macro avg       0.31      0.50      0.38       231
weighted avg      